USE DATABASE RETAIL_CAPSTONE; USE SCHEMA RAW;

-- CUSTOMERS_RAW (12 columns)
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C1 TO CUSTOMER_CODE;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C2 TO FIRST_NAME;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C3 TO LAST_NAME;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C4 TO FULL_NAME;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C5 TO EMAIL;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C6 TO GENDER;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C7 TO CITY;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C8 TO STATE;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C9 TO PHONE;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C10 TO CREATED_AT;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C11 TO UPDATED_AT;
ALTER TABLE CUSTOMERS_RAW RENAME COLUMN C12 TO IS_ACTIVE;

-- PRODUCTS_RAW (5 columns)
ALTER TABLE PRODUCTS_RAW RENAME COLUMN C1 TO PRODUCT_CODE;
ALTER TABLE PRODUCTS_RAW RENAME COLUMN C2 TO PRODUCT_NAME;
ALTER TABLE PRODUCTS_RAW RENAME COLUMN C3 TO CATEGORY;
ALTER TABLE PRODUCTS_RAW RENAME COLUMN C4 TO UNIT_PRICE;
ALTER TABLE PRODUCTS_RAW RENAME COLUMN C5 TO IS_ACTIVE;

-- ORDERS_RAW (6 columns)
ALTER TABLE ORDERS_RAW RENAME COLUMN C1 TO ORDER_ID;
ALTER TABLE ORDERS_RAW RENAME COLUMN C2 TO CUSTOMER_CODE;
ALTER TABLE ORDERS_RAW RENAME COLUMN C3 TO ORDER_DATE;
ALTER TABLE ORDERS_RAW RENAME COLUMN C4 TO STATUS;
ALTER TABLE ORDERS_RAW RENAME COLUMN C5 TO ORDER_CITY;
ALTER TABLE ORDERS_RAW RENAME COLUMN C6 TO ORDER_STATE;

-- ORDER_ITEMS_RAW (6 columns)
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C1 TO ORDER_ITEM_ID;
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C2 TO ORDER_ID;
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C3 TO PRODUCT_CODE;
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C4 TO QUANTITY;
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C5 TO UNIT_PRICE;
ALTER TABLE ORDER_ITEMS_RAW RENAME COLUMN C6 TO LINE_AMOUNT;

-- PAYMENTS_RAW (5 columns)
ALTER TABLE PAYMENTS_RAW RENAME COLUMN C1 TO PAYMENT_ID;
ALTER TABLE PAYMENTS_RAW RENAME COLUMN C2 TO ORDER_ID;
ALTER TABLE PAYMENTS_RAW RENAME COLUMN C3 TO PAYMENT_AMOUNT;
ALTER TABLE PAYMENTS_RAW RENAME COLUMN C4 TO PAYMENT_METHOD;
ALTER TABLE PAYMENTS_RAW RENAME COLUMN C5 TO PAYMENT_DATE;