USE DATABASE RETAIL_CAPSTONE; USE SCHEMA RAW;

DESC TABLE ORDER_ITEMS_RAW;
DESC TABLE PRODUCTS_RAW;
DESC TABLE ORDERS_RAW;
DESC TABLE PAYMENTS_RAW;
DESC TABLE CUSTOMERS_RAW;

-- Monthly revenue
SELECT DATE_TRUNC('MONTH', TRY_TO_TIMESTAMP(o.ORDER_DATE)) AS month,
       SUM(TRY_TO_DECIMAL(TO_VARCHAR(oi.LINE_AMOUNT),18,2)) AS revenue
FROM ORDERS_RAW o
JOIN ORDER_ITEMS_RAW oi ON o.ORDER_ID = oi.ORDER_ID
WHERE o.CUSTOMER_CODE <> '__ORPHAN__' AND oi.PRODUCT_CODE <> '__ORPHAN__'
GROUP BY 1 ORDER BY 1;

-- Top 10 cities by revenue
SELECT o.ORDER_CITY,
       SUM(TRY_TO_DECIMAL(TO_VARCHAR(oi.LINE_AMOUNT),18,2)) AS revenue
FROM ORDERS_RAW o
JOIN ORDER_ITEMS_RAW oi ON o.ORDER_ID = oi.ORDER_ID
WHERE o.CUSTOMER_CODE <> '__ORPHAN__' AND oi.PRODUCT_CODE <> '__ORPHAN__'
  AND o.ORDER_CITY IS NOT NULL
GROUP BY o.ORDER_CITY
ORDER BY revenue DESC
LIMIT 10;

-- Top 10 products by revenue
SELECT p.PRODUCT_NAME, SUM(TRY_TO_DECIMAL(TO_VARCHAR(oi.LINE_AMOUNT),18,2)) AS revenue
FROM ORDER_ITEMS_RAW oi
JOIN PRODUCTS_RAW p ON oi.PRODUCT_CODE = p.PRODUCT_CODE
WHERE oi.PRODUCT_CODE <> '__ORPHAN__'
GROUP BY p.PRODUCT_NAME ORDER BY revenue DESC LIMIT 10;

-- Customer lifetime value (CLV) — total spend per customer
SELECT c.CUSTOMER_CODE, c.FULL_NAME,
       SUM(TRY_TO_DECIMAL(TO_VARCHAR(oi.LINE_AMOUNT),18,2)) AS lifetime_value
FROM CUSTOMERS_RAW c
JOIN ORDERS_RAW o ON c.CUSTOMER_CODE = o.CUSTOMER_CODE
JOIN ORDER_ITEMS_RAW oi ON o.ORDER_ID = oi.ORDER_ID
WHERE o.CUSTOMER_CODE <> '__ORPHAN__' AND oi.PRODUCT_CODE <> '__ORPHAN__'
GROUP BY 1,2 ORDER BY lifetime_value DESC LIMIT 20;
